export const US_SCHOOLS: string[] = [
  "Harvard University",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "University of Pennsylvania",
  "Brown University",
  "Dartmouth College",
  "Cornell University",
  "Stanford University",
  "Massachusetts Institute of Technology",
  "California Institute of Technology",
  "Duke University",
  "Northwestern University",
  "University of Chicago",
  "Johns Hopkins University",
  "Rice University",
  "Vanderbilt University",
  "Washington University in St. Louis",
  "Emory University",
  "Georgetown University",
  "Carnegie Mellon University",
  "University of Notre Dame",
  "University of Southern California",
  "New York University",
  "Boston University",
  "Boston College",
  "Tufts University",
  "Wake Forest University",
  "Brandeis University",
  "Case Western Reserve University",
  "Tulane University",
  "Villanova University",
  "Lehigh University",
  "Northeastern University",
  "George Washington University",
  "Syracuse University",
  "Fordham University",
  "American University",
  "Santa Clara University",
  "Loyola Marymount University",
  "University of Miami",
  "Southern Methodist University",
  "Pepperdine University",
  "Gonzaga University",
  "Marquette University",
  "Creighton University",
  "University of San Diego",
  "University of San Francisco",
  "Stevens Institute of Technology",
  "Worcester Polytechnic Institute",
  "Rensselaer Polytechnic Institute",
  "Rochester Institute of Technology",
  "Drexel University",
  "University of Denver",
  "DePaul University",
  "Seton Hall University",
  "University of Dayton",
  "Xavier University",
  "University of Tulsa",
  "University of the Pacific",
  "Chapman University",
  "Elon University",
  "Quinnipiac University",
  "Fairfield University",
  "University of Scranton",
  "Loyola University Chicago",
  "Loyola University Maryland",
  "Loyola University New Orleans",
  "Seattle University",
  "University of Portland",
  "University of Detroit Mercy",
  "Samford University",
  "Belmont University",
  "Mercer University",
  "Stetson University",
  "Butler University",
  "Drake University",
  "Bradley University",
  "Valparaiso University",
  "University of California, Berkeley",
  "University of California, Los Angeles",
  "University of California, San Diego",
  "University of California, Santa Barbara",
  "University of California, Davis",
  "University of California, Irvine",
  "University of California, Santa Cruz",
  "University of California, Riverside",
  "University of California, Merced",
  "San Diego State University",
  "San Jose State University",
  "Cal Poly San Luis Obispo",
  "Cal Poly Pomona",
  "San Francisco State University",
  "Sacramento State University",
  "Long Beach State University",
  "Fresno State University",
  "Cal State Fullerton",
  "Cal State Northridge",
  "Cal State Los Angeles",
  "Cal State Dominguez Hills",
  "Cal State East Bay",
  "Cal State Bakersfield",
  "Cal State Channel Islands",
  "Cal State Monterey Bay",
  "Cal State San Bernardino",
  "Cal State San Marcos",
  "Cal State Stanislaus",
  "Humboldt State University",
  "Sonoma State University",
  "Chico State University",
  "University of Michigan",
  "University of Virginia",
  "University of North Carolina at Chapel Hill",
  "University of Texas at Austin",
  "University of Wisconsin-Madison",
  "University of Florida",
  "University of Georgia",
  "University of Illinois Urbana-Champaign",
  "University of Washington",
  "University of Maryland, College Park",
  "Ohio State University",
  "Penn State University",
  "Indiana University Bloomington",
  "University of Minnesota Twin Cities",
  "University of Iowa",
  "University of Colorado Boulder",
  "University of Oregon",
  "University of Arizona",
  "Arizona State University",
  "Michigan State University",
  "Purdue University",
  "Rutgers University",
  "University of Connecticut",
  "University of Massachusetts Amherst",
  "University of Pittsburgh",
  "Virginia Tech",
  "Texas A&M University",
  "North Carolina State University",
  "Georgia Institute of Technology",
  "University of South Carolina",
  "University of Kentucky",
  "University of Tennessee",
  "University of Alabama",
  "University of Missouri",
  "University of Kansas",
  "University of Oklahoma",
  "University of Nebraska-Lincoln",
  "University of Arkansas",
  "University of Mississippi",
  "Louisiana State University",
  "Iowa State University",
  "Kansas State University",
  "Oklahoma State University",
  "Oregon State University",
  "Washington State University",
  "Colorado State University",
  "University of Utah",
  "University of New Mexico",
  "University of Nevada, Las Vegas",
  "University of Nevada, Reno",
  "University of Hawaii at Manoa",
  "University of Idaho",
  "University of Montana",
  "University of Wyoming",
  "University of South Dakota",
  "University of North Dakota",
  "University of Vermont",
  "University of New Hampshire",
  "University of Maine",
  "University of Rhode Island",
  "University of Delaware",
  "West Virginia University",
  "University of Louisville",
  "University of Cincinnati",
  "University of Houston",
  "University of North Texas",
  "University of Texas at Dallas",
  "University of Texas at San Antonio",
  "University of Texas at Arlington",
  "University of Texas at El Paso",
  "Florida State University",
  "University of Central Florida",
  "University of South Florida",
  "Florida International University",
  "Florida Atlantic University",
  "Florida A&M University",
  "Georgia State University",
  "Clemson University",
  "Auburn University",
  "University of Alabama at Birmingham",
  "Mississippi State University",
  "Baylor University",
  "Texas Christian University",
  "Texas Tech University",
  "University of Akron",
  "University of Toledo",
  "Bowling Green State University",
  "Ball State University",
  "Western Michigan University",
  "Central Michigan University",
  "Eastern Michigan University",
  "Northern Illinois University",
  "Southern Illinois University",
  "Illinois State University",
  "University of Wisconsin-Milwaukee",
  "University of Minnesota Duluth",
  "University at Buffalo",
  "Stony Brook University",
  "Binghamton University",
  "University at Albany",
  "Temple University",
  "George Mason University",
  "James Madison University",
  "Old Dominion University",
  "College of William & Mary",
  "University of Massachusetts Boston",
  "University of Massachusetts Lowell",
  "University of Maryland, Baltimore County",
  "Towson University",
  "Williams College",
  "Amherst College",
  "Swarthmore College",
  "Pomona College",
  "Wellesley College",
  "Bowdoin College",
  "Claremont McKenna College",
  "Middlebury College",
  "Carleton College",
  "Haverford College",
  "Harvey Mudd College",
  "Vassar College",
  "Colgate University",
  "Hamilton College",
  "Wesleyan University",
  "Bates College",
  "Colby College",
  "Grinnell College",
  "Davidson College",
  "Washington and Lee University",
  "Barnard College",
  "Smith College",
  "Mount Holyoke College",
  "Bryn Mawr College",
  "Oberlin College",
  "Macalester College",
  "Kenyon College",
  "Bucknell University",
  "College of the Holy Cross",
  "Lafayette College",
  "Trinity College",
  "Connecticut College",
  "Union College",
  "Skidmore College",
  "Whitman College",
  "Reed College",
  "Colorado College",
  "Occidental College",
  "Scripps College",
  "Pitzer College",
  "Furman University",
  "Rhodes College",
  "Centre College",
  "Denison University",
  "DePauw University",
  "Dickinson College",
  "Franklin & Marshall College",
  "Gettysburg College",
  "St. Olaf College",
  "Sewanee: The University of the South",
  "University of Richmond",
  "Wabash College",
  "Wheaton College",
  "Whitworth University",
  "Willamette University",
  "Lewis & Clark College",
  "Sarah Lawrence College",
  "Bennington College",
  "Hampshire College",
  "Bard College",
  "Howard University",
  "Spelman College",
  "Morehouse College",
  "Hampton University",
  "Tuskegee University",
  "Fisk University",
  "Clark Atlanta University",
  "North Carolina A&T State University",
  "Xavier University of Louisiana",
  "Tennessee State University",
  "Jackson State University",
  "Prairie View A&M University",
  "Morgan State University",
  "Delaware State University",
  "Bethune-Cookman University",
  "Dillard University",
  "Grambling State University",
  "Norfolk State University",
  "Alabama State University",
  "Alcorn State University",
  "Benedict College",
  "Bowie State University",
  "Cheyney University of Pennsylvania",
  "Coppin State University",
  "Elizabeth City State University",
  "Langston University",
  "Lincoln University",
  "Southern University",
  "Virginia State University",
  "Winston-Salem State University",
  "Rhode Island School of Design",
  "School of the Art Institute of Chicago",
  "Parsons School of Design",
  "Pratt Institute",
  "Cooper Union",
  "California College of the Arts",
  "Maryland Institute College of Art",
  "Savannah College of Art and Design",
  "School of Visual Arts",
  "ArtCenter College of Design",
  "Otis College of Art and Design",
  "Ringling College of Art and Design",
  "Berklee College of Music",
  "Juilliard School",
  "Manhattan School of Music",
  "New England Conservatory",
  "United States Military Academy (West Point)",
  "United States Naval Academy",
  "United States Air Force Academy",
  "United States Coast Guard Academy",
  "United States Merchant Marine Academy",
  "Appalachian State University",
  "College of Charleston",
  "University of North Carolina at Charlotte",
  "University of North Carolina at Greensboro",
  "University of North Carolina at Wilmington",
  "East Carolina University",
  "Western Carolina University",
  "University of Alabama in Huntsville",
  "Troy University",
  "University of West Georgia",
  "Kennesaw State University",
  "Georgia Southern University",
  "Valdosta State University",
  "University of North Florida",
  "University of West Florida",
  "Jacksonville University",
  "Rollins College",
  "Embry-Riddle Aeronautical University",
  "University of Tampa",
  "Coastal Carolina University",
  "Winthrop University",
  "Francis Marion University",
  "Murray State University",
  "Eastern Kentucky University",
  "Western Kentucky University",
  "Northern Kentucky University",
  "Middle Tennessee State University",
  "Austin Peay State University",
  "University of Memphis",
  "University of Southern Mississippi",
  "University of Central Arkansas",
  "Arkansas State University",
  "Lamar University",
  "Stephen F. Austin State University",
  "Sam Houston State University",
  "Tarleton State University",
  "Texas State University",
  "University of Texas Rio Grande Valley",
  "New Mexico State University",
  "University of Northern Colorado",
  "Montana State University",
  "Boise State University",
  "Idaho State University",
  "Weber State University",
  "Utah State University",
  "Brigham Young University",
  "Portland State University",
  "Eastern Washington University",
  "Central Washington University",
  "Western Washington University",
  "University of Alaska Anchorage",
  "University of Alaska Fairbanks",
  "Minnesota State University, Mankato",
  "St. Cloud State University",
  "University of Wisconsin-La Crosse",
  "University of Wisconsin-Eau Claire",
  "University of Wisconsin-Stevens Point",
  "University of Wisconsin-Oshkosh",
  "University of Wisconsin-Green Bay",
  "University of Wisconsin-Whitewater",
  "University of Wisconsin-Platteville",
  "University of Wisconsin-Stout",
  "Northern Michigan University",
  "Grand Valley State University",
  "Ferris State University",
  "Saginaw Valley State University",
  "University of Northern Iowa",
  "Truman State University",
  "Missouri State University",
  "Southeast Missouri State University",
  "Northwest Missouri State University",
  "Wichita State University",
  "Emporia State University",
  "Fort Hays State University",
  "Pittsburg State University",
  "University of Central Oklahoma",
  "University of Nebraska at Omaha",
  "University of Nebraska at Kearney",
  "South Dakota State University",
  "North Dakota State University",
  "Santa Monica College",
  "Pasadena City College",
  "De Anza College",
  "Foothill College",
  "Diablo Valley College",
  "Orange Coast College",
  "Irvine Valley College",
  "El Camino College",
  "Glendale Community College",
  "Mt. San Antonio College",
  "Santa Barbara City College",
  "College of San Mateo",
  "City College of San Francisco",
  "Los Angeles City College",
  "Miami Dade College",
  "Broward College",
  "Valencia College",
  "Hillsborough Community College",
  "Santa Fe College",
  "Lone Star College",
  "Austin Community College",
  "Dallas College",
  "Houston Community College",
  "Tarrant County College",
  "Maricopa Community Colleges",
  "Pima Community College",
  "Central Piedmont Community College",
  "Wake Technical Community College",
  "Northern Virginia Community College",
  "Tidewater Community College",
  "Montgomery College",
  "Community College of Baltimore County",
  "Prince George's Community College",
  "Bergen Community College",
  "Middlesex County College",
  "Raritan Valley Community College",
  "Suffolk County Community College",
  "Nassau Community College",
  "Westchester Community College",
  "Bunker Hill Community College",
  "MassBay Community College",
  "Community College of Rhode Island",
  "Cuyahoga Community College",
  "Columbus State Community College",
  "Sinclair Community College",
  "Ivy Tech Community College",
  "College of DuPage",
  "Harper College",
  "Joliet Junior College",
  "Triton College",
  "Madison Area Technical College",
  "Milwaukee Area Technical College",
  "Minneapolis Community and Technical College",
  "Hennepin Technical College",
  "Johnson County Community College",
  "St. Louis Community College",
  "Metropolitan Community College",
  "Portland Community College",
  "Bellevue College",
  "Green River College",
  "Highline College",
  "Salt Lake Community College",
  "Brigham Young University-Idaho",
  "Liberty University",
  "Grand Canyon University",
  "University of Phoenix",
  "Full Sail University",
  "Champlain College",
  "Ithaca College",
  "Marist College",
  "Siena College",
  "St. Lawrence University",
  "Hobart and William Smith Colleges",
  "Clarkson University",
  "University of Rochester",
  "Alfred University",
  "Le Moyne College",
  "Manhattan College",
  "Pace University",
  "St. John's University",
  "Hofstra University",
  "Adelphi University",
  "Wagner College",
  "Long Island University",
  "Sacred Heart University",
  "University of Hartford",
  "University of New Haven",
  "Assumption University",
  "Stonehill College",
  "Providence College",
  "Bryant University",
  "Salve Regina University",
  "Roger Williams University",
  "Bentley University",
  "Babson College",
  "Olin College of Engineering",
  "Wentworth Institute of Technology",
  "Suffolk University",
  "Clark University",
  "University of Saint Joseph",
  "University of Bridgeport",
  "Monmouth University",
  "Rider University",
  "Rowan University",
  "Stockton University",
  "The College of New Jersey",
  "Widener University",
  "Arcadia University",
  "La Salle University",
  "Saint Joseph's University",
  "Duquesne University",
  "Robert Morris University",
  "Chatham University",
  "Point Park University",
  "Allegheny College",
  "Muhlenberg College",
  "Susquehanna University",
  "Ursinus College",
  "Elizabethtown College",
  "York College of Pennsylvania",
  "Messiah University",
  "Misericordia University",
  "King's College",
  "Wilkes University",
  "Marywood University",
  "Hood College",
  "McDaniel College",
  "Washington College",
  "St. Mary's College of Maryland",
  "University of Mary Washington",
  "Radford University",
  "Longwood University",
  "Christopher Newport University",
  "Roanoke College",
  "Hampden-Sydney College",
  "Randolph-Macon College",
  "Virginia Military Institute",
  "Lynchburg University",
  "Shenandoah University",
  "Averett University",
  "High Point University",
  "Campbell University",
  "Gardner-Webb University",
  "Catawba College",
  "Guilford College",
  "Warren Wilson College",
  "Lander University",
  "Presbyterian College",
  "Wofford College",
  "Erskine College",
  "Newberry College",
  "Converse University",
  "Coker University",
  "Berry College",
  "Oglethorpe University",
  "LaGrange College",
  "Shorter University",
  "Piedmont University",
  "University of Montevallo",
  "Birmingham-Southern College",
  "Spring Hill College",
  "Hendrix College",
  "Lyon College",
  "Harding University",
  "John Brown University",
  "University of the Ozarks",
  "Millsaps College",
  "Belhaven University",
  "Mississippi College",
  "Centenary College of Louisiana",
  "Louisiana Tech University",
  "University of Louisiana at Lafayette",
  "University of Louisiana at Monroe",
  "Nicholls State University",
  "McNeese State University",
  "Northwestern State University",
  "Southeastern Louisiana University",
  "Schreiner University",
  "Trinity University",
  "St. Edward's University",
  "University of the Incarnate Word",
  "Texas Lutheran University",
  "St. Mary's University",
  "Abilene Christian University",
  "Hardin-Simmons University",
  "Howard Payne University",
  "Southwestern University",
  "Austin College",
  "University of Dallas",
  "Texas Wesleyan University",
  "Oklahoma Baptist University",
  "Oklahoma City University",
  "University of Science and Arts of Oklahoma",
  "Oral Roberts University",
  "Baker University",
  "Washburn University",
  "Friends University",
  "Bethel College",
  "McPherson College",
  "Ottawa University",
  "Nebraska Wesleyan University",
  "Hastings College",
  "Doane University",
  "College of Saint Mary",
  "Augustana University",
  "University of Sioux Falls",
  "Dakota Wesleyan University",
  "University of Jamestown",
  "Concordia College",
  "Gustavus Adolphus College",
  "Hamline University",
  "Augsburg University",
  "Bethel University",
  "University of St. Thomas",
  "College of Saint Benedict",
  "Saint John's University",
  "Winona State University",
  "Lawrence University",
  "Beloit College",
  "Ripon College",
  "Carroll University",
  "Edgewood College",
  "Alverno College",
  "Hope College",
  "Calvin University",
  "Kalamazoo College",
  "Albion College",
  "Alma College",
  "Adrian College",
  "Hillsdale College",
  "Aquinas College",
  "Cornerstone University",
  "Olivet Nazarene University",
  "Illinois Wesleyan University",
  "Augustana College",
  "Knox College",
  "Lake Forest College",
  "Monmouth College",
  "North Central College",
  "Wheaton College (IL)",
  "Elmhurst University",
  "Millikin University",
  "McKendree University",
  "Eastern Illinois University",
  "Western Illinois University",
  "Southern Illinois University Edwardsville",
  "Wittenberg University",
  "Ohio Wesleyan University",
  "Wooster College",
  "Otterbein University",
  "Capital University",
  "Mount Union University",
  "Muskingum University",
  "Marietta College",
  "Heidelberg University",
  "Baldwin Wallace University",
  "John Carroll University",
  "Hiram College",
  "Youngstown State University",
  "Earlham College",
  "Hanover College",
  "Manchester University",
  "Rose-Hulman Institute of Technology",
  "University of Evansville",
  "Taylor University",
  "Anderson University",
  "Franklin College",
  "Transylvania University",
  "Berea College",
  "Asbury University",
  "Thomas More University",
  "Bellarmine University",
  "Spalding University",
  "University of Findlay",
  "Tiffin University",
  "Cedarville University",
  "Malone University",
  "Walsh University",
  "Ashland University",
  "University of Mount Union",
  "Illinois Institute of Technology",
  "New Jersey Institute of Technology",
  "Florida Institute of Technology",
  "Virginia Polytechnic Institute and State University",
  "Kettering University",
  "Milwaukee School of Engineering",
  "Webb Institute",
  "SUNY College at Geneseo",
  "SUNY College at New Paltz",
  "SUNY College at Oswego",
  "SUNY College at Plattsburgh",
  "SUNY College at Cortland",
  "SUNY College at Oneonta",
  "SUNY College at Potsdam",
  "SUNY College at Brockport",
  "SUNY College at Fredonia",
  "SUNY Polytechnic Institute",
];
